version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - echo Fetching Firebase credentials...
      - CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id prod/cafe-campus | jq -r .SecretString)
      - export REACT_APP_FIREBASE_API_KEY=$(echo $CREDENTIALS | jq -r .apiKey)
      - export REACT_APP_FIREBASE_AUTH_DOMAIN=$(echo $CREDENTIALS | jq -r .authDomain)
      - export REACT_APP_FIREBASE_PROJECT_ID=$(echo $CREDENTIALS | jq -r .projectId)
      - export REACT_APP_FIREBASE_STORAGE_BUCKET=$(echo $CREDENTIALS | jq -r .storageBucket)
      - export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$(echo $CREDENTIALS | jq -r .messagingSenderId)
      - export REACT_APP_FIREBASE_APP_ID=$(echo $CREDENTIALS | jq -r .appId)
      - export REACT_APP_FIREBASE_DATABASE_URL=$(echo $CREDENTIALS | jq -r .databaseURL)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://cafe-campus/
      - echo Build completed on `date`
